services:
  backend:
    image: ghcr.io/victorfedorov/amnezia-vpn-ui/backend:latest
    container_name: amnezia_backend
    volumes:
      - db_data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./data/vpn_manager.db
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/victorfedorov/amnezia-vpn-ui/frontend:latest
    container_name: amnezia_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
    driver: local
