"""Remove protocol from Server model

Revision ID: 0b6b4ea58ab8
Revises: 2163c4bf7acd
Create Date: 2026-01-31 22:01:57.037244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6b4ea58ab8'
down_revision: Union[str, None] = '2163c4bf7acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'protocol')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('protocol', sa.VARCHAR(length=11), nullable=False))
    # ### end Alembic commands ###
