"""Initial migration

Revision ID: 2163c4bf7acd
Revises: 
Create Date: 2026-01-31 20:18:39.180998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2163c4bf7acd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('ssh_user', sa.String(length=100), nullable=False),
    sa.Column('ssh_password', sa.String(length=255), nullable=True),
    sa.Column('ssh_key_path', sa.String(length=500), nullable=True),
    sa.Column('protocol', sa.Enum('AWG', 'VLESS', 'VMESS', 'TROJAN', 'SHADOWSOCKS', name='protocoltype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', name='serverstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_servers_id'), 'servers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('client_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.Enum('AWG', 'VLESS', 'VMESS', 'TROJAN', 'SHADOWSOCKS', name='protocoltype'), nullable=False),
    sa.Column('config_content', sa.Text(), nullable=False),
    sa.Column('peer_public_key', sa.String(length=255), nullable=True),
    sa.Column('client_uuid', sa.String(length=255), nullable=True),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_handshake', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_server', 'client_configs', ['user_id', 'server_id'], unique=False)
    op.create_index(op.f('ix_client_configs_client_uuid'), 'client_configs', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_client_configs_id'), 'client_configs', ['id'], unique=False)
    op.create_index(op.f('ix_client_configs_peer_public_key'), 'client_configs', ['peer_public_key'], unique=True)
    op.create_index(op.f('ix_client_configs_server_id'), 'client_configs', ['server_id'], unique=False)
    op.create_index(op.f('ix_client_configs_user_id'), 'client_configs', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_type', sa.Enum('TRIAL', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'LIFETIME', name='subscriptiontype'), nullable=False),
    sa.Column('subscription_start', sa.DateTime(), nullable=False),
    sa.Column('subscription_end', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('traffic_limit_gb', sa.Integer(), nullable=True),
    sa.Column('traffic_used_gb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'subscriptions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_active'), 'subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscription_end'), 'subscriptions', ['subscription_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('connection_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['client_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_event_time', 'connection_events', ['config_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_connection_events_config_id'), 'connection_events', ['config_id'], unique=False)
    op.create_index(op.f('ix_connection_events_id'), 'connection_events', ['id'], unique=False)
    op.create_index(op.f('ix_connection_events_timestamp'), 'connection_events', ['timestamp'], unique=False)
    op.create_table('traffic_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('bytes_received', sa.Integer(), nullable=True),
    sa.Column('bytes_sent', sa.Integer(), nullable=True),
    sa.Column('speed_download', sa.Float(), nullable=True),
    sa.Column('speed_upload', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['client_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_timestamp', 'traffic_history', ['config_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_traffic_history_config_id'), 'traffic_history', ['config_id'], unique=False)
    op.create_index(op.f('ix_traffic_history_id'), 'traffic_history', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_history_timestamp'), 'traffic_history', ['timestamp'], unique=False)
    op.create_table('traffic_stats_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_bytes_received', sa.Integer(), nullable=True),
    sa.Column('total_bytes_sent', sa.Integer(), nullable=True),
    sa.Column('avg_speed_download', sa.Float(), nullable=True),
    sa.Column('avg_speed_upload', sa.Float(), nullable=True),
    sa.Column('max_speed_download', sa.Float(), nullable=True),
    sa.Column('max_speed_upload', sa.Float(), nullable=True),
    sa.Column('connection_time_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['client_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_date', 'traffic_stats_daily', ['config_id', 'date'], unique=False)
    op.create_index(op.f('ix_traffic_stats_daily_config_id'), 'traffic_stats_daily', ['config_id'], unique=False)
    op.create_index(op.f('ix_traffic_stats_daily_date'), 'traffic_stats_daily', ['date'], unique=False)
    op.create_index(op.f('ix_traffic_stats_daily_id'), 'traffic_stats_daily', ['id'], unique=False)
    op.create_table('traffic_stats_hourly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('hour_start', sa.DateTime(), nullable=False),
    sa.Column('total_bytes_received', sa.Integer(), nullable=True),
    sa.Column('total_bytes_sent', sa.Integer(), nullable=True),
    sa.Column('avg_speed_download', sa.Float(), nullable=True),
    sa.Column('avg_speed_upload', sa.Float(), nullable=True),
    sa.Column('max_speed_download', sa.Float(), nullable=True),
    sa.Column('max_speed_upload', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['client_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_hour', 'traffic_stats_hourly', ['config_id', 'hour_start'], unique=False)
    op.create_index(op.f('ix_traffic_stats_hourly_config_id'), 'traffic_stats_hourly', ['config_id'], unique=False)
    op.create_index(op.f('ix_traffic_stats_hourly_hour_start'), 'traffic_stats_hourly', ['hour_start'], unique=False)
    op.create_index(op.f('ix_traffic_stats_hourly_id'), 'traffic_stats_hourly', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_stats_hourly_id'), table_name='traffic_stats_hourly')
    op.drop_index(op.f('ix_traffic_stats_hourly_hour_start'), table_name='traffic_stats_hourly')
    op.drop_index(op.f('ix_traffic_stats_hourly_config_id'), table_name='traffic_stats_hourly')
    op.drop_index('idx_config_hour', table_name='traffic_stats_hourly')
    op.drop_table('traffic_stats_hourly')
    op.drop_index(op.f('ix_traffic_stats_daily_id'), table_name='traffic_stats_daily')
    op.drop_index(op.f('ix_traffic_stats_daily_date'), table_name='traffic_stats_daily')
    op.drop_index(op.f('ix_traffic_stats_daily_config_id'), table_name='traffic_stats_daily')
    op.drop_index('idx_config_date', table_name='traffic_stats_daily')
    op.drop_table('traffic_stats_daily')
    op.drop_index(op.f('ix_traffic_history_timestamp'), table_name='traffic_history')
    op.drop_index(op.f('ix_traffic_history_id'), table_name='traffic_history')
    op.drop_index(op.f('ix_traffic_history_config_id'), table_name='traffic_history')
    op.drop_index('idx_config_timestamp', table_name='traffic_history')
    op.drop_table('traffic_history')
    op.drop_index(op.f('ix_connection_events_timestamp'), table_name='connection_events')
    op.drop_index(op.f('ix_connection_events_id'), table_name='connection_events')
    op.drop_index(op.f('ix_connection_events_config_id'), table_name='connection_events')
    op.drop_index('idx_config_event_time', table_name='connection_events')
    op.drop_table('connection_events')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_subscription_end'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_active'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index('idx_user_active', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_client_configs_user_id'), table_name='client_configs')
    op.drop_index(op.f('ix_client_configs_server_id'), table_name='client_configs')
    op.drop_index(op.f('ix_client_configs_peer_public_key'), table_name='client_configs')
    op.drop_index(op.f('ix_client_configs_id'), table_name='client_configs')
    op.drop_index(op.f('ix_client_configs_client_uuid'), table_name='client_configs')
    op.drop_index('idx_user_server', table_name='client_configs')
    op.drop_table('client_configs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_servers_id'), table_name='servers')
    op.drop_table('servers')
    # ### end Alembic commands ###
