"""Add cache fields to ClientConfig

Revision ID: 363a3fc9ce31
Revises: 0b6b4ea58ab8
Create Date: 2026-01-31 22:36:04.730509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363a3fc9ce31'
down_revision: Union[str, None] = '0b6b4ea58ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_configs', sa.Column('allowed_ips', sa.String(length=255), nullable=True))
    op.add_column('client_configs', sa.Column('endpoint', sa.String(length=255), nullable=True))
    op.add_column('client_configs', sa.Column('bytes_received', sa.Integer(), nullable=True))
    op.add_column('client_configs', sa.Column('bytes_sent', sa.Integer(), nullable=True))
    op.add_column('client_configs', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('client_configs', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_configs', 'last_seen')
    op.drop_column('client_configs', 'is_online')
    op.drop_column('client_configs', 'bytes_sent')
    op.drop_column('client_configs', 'bytes_received')
    op.drop_column('client_configs', 'endpoint')
    op.drop_column('client_configs', 'allowed_ips')
    # ### end Alembic commands ###
